core/urls.py
from django.urls import path, include
from .views import home_view, crypto_view, stocks_view, base_view, sports_view

app_name = "core"

urlpatterns = [
    path("", base_view, name="base"),
    path("home", home_view, name="home"),
    path("crypto", crypto_view, name="crypto"),
    path("stocks", stocks_view, name="stocks"),
    path("sports", sports_view, name="sports"),
    
]

kripto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]

users/urls.py
from django.urls import path
from .views import ( logout_view, 
login_view, 
signup_view, 
passwordreset_view, 
forgot_password_request_view, 
forgot_password_response_view,
)
app_name="users"

urlpatterns = [
       path("logout/", logout_view, name="logout"),
       path("login/", login_view, name="login"),
       path("signup/", signup_view, name="signup"),
       path("passwordreset/", passwordreset_view, name="password-reset"),
       path("forgotpassword/", forgot_password_request_view, name="forgot-password"),
       path("forgotpassword/<token>/", forgot_password_response_view, name="forgot-password-response"),
]

core/models.py
from django.db import models

# Create your models here.

class Test(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return str(self.id)
    
class Position(models.Model):
    name = models.CharField(max_length=200)
    image = models.URLField()
    price = models.CharField(max_length=200)
    rank = models.CharField(max_length=10)
    market_cap = models.CharField(max_length=200)
    
    def __str__(self):
        return str(self,name)

core/views.py
from django.shortcuts import render
import requests
from django.http import HttpResponse

def base_view(request):
    return render(request, "core/base.html")

def home_view(request):
    return render(request, "core/home.html")

def sports_view(request):
    return render(request, "core/sports.html")



def crypto_view(request):
    url="https://api.coingecko.com/api/v3/coins/markets?vs_currency=btc&order=market_cap_desc&per_page=100&page=1&sparkline=false"
    data = requests.get(url).json()
    #return HttpResponse(data)
    context = {'data':data}
    return render(request, "core/crypto.html", context)

def stocks_view(request):
    return render(request, "core/stocks.html")

core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NewSence</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
   <style>
    @import url("https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900");
    body{
      background-color: rgb(255, 255, 255);
    }

    .animate-charcter
{
   text-transform: uppercase;
  background-image: linear-gradient(
    -225deg,
    #231557 0%,
    #44107a 29%,
    #ff1361 67%,
    #fff800 100%
  );
  background-size: auto auto;
  background-clip: border-box;
  background-size: 200% auto;
  color: #fff;
  padding: 30px;
  background-clip: text;
  text-fill-color: transparent;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  animation: textclip 2s linear infinite;
  display: inline-block;
      font-size: 190px;
}

@keyframes textclip {
  to {
    background-position: 200% center;
  }
}

.waviy {
  position: relative;
  align-items: center;
}
.waviy span {
  position: relative;
  display: inline-block;
  font-size: 45px;
  color: rgb(65, 65, 65);
  padding: 10px;
  text-transform: uppercase;
  animation: flip 2s infinite;
  animation-delay: calc(.2s * var(--i))
}
@keyframes flip {
  0%,80% {
    transform: rotateY(360deg) 
  }
}

.btnh{
  text-align: center;
  text-decoration: none;
}
.button {
  border-radius: 4px;
  background-color: #00ffee;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 15px;
  padding: 20px;
  width: 100px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 2px;
  text-decoration: none;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}
   </style>

  <body>
    <div class="container">
    {% include "core/navbar.html" %}  
    {% include "core/messages.html" %} 

    {% block content %}
     <div class="hero">  
      
      <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
              <div class="container">
                <div class="row">
                  <div class="col-md-12 text-center">
                    <h3 class="animate-charcter">NewsRadar</h3>
                  </div>
                  <body>
                    <div class="waviy">
                      <span style="--i:1">Resources</span>
                      <span style="--i:2">For </span>
                      <span style="--i:3">Future</span>
                     </div>
                     <div>
                      <div class="btnh">
                      <li>
                        <a href="{% url 'users:signup' %}"><button class="button" ><span>Signup </span></button></a>
                        <a href="{% url 'users:login' %}"><button class="button" ><span>Login </span></button></a>
                      </li>
                    </div>
                     </div>
                   </body>
                </div>
              </div>
            </div>
        </div>
    </header>
  
 </div>

    {% endblock content %}
           
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/crypto.html
 <!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>
    <style>

        body{
            width: 100%;
            height: auto;
            overflow: auto;
            background-color: white;
        }

h1 {

    margin: 0 auto;
    text-align: center;
    padding: 20px ;
}
h3 {
    text-align: center;
}
    </style>
    <body>
      
        {% include "core/navbar.html" %}  
        {% include "core/messages.html" %} 
        <div>
            {% if user.is_authenticated %}
            {% block content%}



            <h1>CRYPTO</h1>
     
            <div>
                <div class="cryptohopper-web-widget" data-id="2"></div>
                <script src="https://www.cryptohopper.com/widgets/js/script"></script>
                
            </div>
     

  <!-- TradingView Widget BEGIN -->

<div class="tradingview-widget-container" style="display: flex; justify-content: center">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/markets/cryptocurrencies/prices-all/" rel="noopener" target="_blank"><span class="blue-text"></span></a> </div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-screener.js" async>
    {
    "width": 1400,
    "height": 300,
    "defaultColumn": "overview",
    "screener_type": "crypto_mkt",
    "displayCurrency": "USD",
    "colorTheme": "light",
    "locale": "en"
  }
    </script>

    
  </div>
  <!-- TradingView Widget END -->

  <div class="cryptohopper-web-widget" data-id="5"></div>
  <script src="https://www.cryptohopper.com/widgets/js/script"></script>


            {% endblock content %}
            {% else %}

            <h1>ERROR 404 not Found</h1>
            {% endif %}
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    </body>
</html>

core/templates/core/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kripto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
   <style>

    body{
        background-color: white;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica,
    Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    }
    h1 {
  color: rgb(34, 34, 34);
  font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
  font-size: 50px;
    margin: 0 auto;
    text-align: center;
    padding: 50px ;
   }


.main-container {
  padding: 30px;
}

/* HEADING */

.heading {
  text-align: center;
}

.heading__title {
  font-weight: 600;
}

.heading__credits {
  margin: 10px 0px;
  color: #888888;
  font-size: 25px;
  transition: all 0.5s;
}

.heading__link {
  text-decoration: none;
}

.heading__credits .heading__link {
  color: inherit;
}

/* CARDS */

.cards {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.card {
  margin: 20px;
  padding: 10px;
  width: 300px;
  height: 300px;
  display: grid;
  grid-template-rows: 20px 50px 1fr 50px;
  border-radius: 10px;
  box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.25);
  transition: all 0.2s;
}

.card:hover {
  box-shadow: 0px 6px 10px rgba(0, 0, 0, 0.4);
  transform: scale(1.1);
}

.card__link,
.card__exit,
.card__icon {
  position: relative;
  text-decoration: none;
  color: rgba(255, 255, 255, 0.9);
  text-align: center;
}

.card__link::after {
  position: absolute;
  top: 25px;
  left: 0;
  content: "";
  width: 0%;
  height: 3px;
  background-color: rgba(255, 255, 255, 0.6);
  transition: all 0.5s;
}

.card__link:hover::after {
  width: 100%;
}

.card__exit {
  grid-row: 1/2;
  justify-self: end;
}

.card__icon {
  grid-row: 2/3;
  font-size: 10px;
}

.card__title {
  grid-row: 3/4;
  font-weight: 400;
  color: #ffffff;
}

.card__apply {
  grid-row: 4/5;
  align-self: center;
}

/* CARD BACKGROUNDS */

.card-1 {
  background: radial-gradient(#ff4949, #000000);
}

.card-2 {
  background: radial-gradient(#2dff2d, #000000);
}

.card-3 {
  background: radial-gradient(#76b2fe, #000000);
}

.card-4 {
  background: radial-gradient(#60efbc, #000000);
}

.card-5 {
  background: radial-gradient(#f588d8, #000000);
}

/* RESPONSIVE */

@media (max-width: 1600px) {
  .cards {
    justify-content: center;
  }
}
   </style>

  <body>
    <div class="container">
    {% if user.is_authenticated %}
    {% include "core/navbar.html" %}  
    {% include "core/messages.html" %} 
 
    {% block content %}
    <div class="main-container">
        <div class="heading">
          <p class="heading__credits"><a class="heading__link" target="_blank" href="https://dribbble.com/sl">Resources for Future</a></p>
        </div>
        <div class="cards">
          <div class="card card-1">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h1 class="card__title">CRYPTO</h1>
            <p class="card__apply">
              <a class="card__link" href="{% url 'core:crypto' %}">LOOK<i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
          <div class="card card-2">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h1 class="card__title">STOCKS</h1>
            <p class="card__apply">
              <a class="card__link" href="{% url 'core:stocks' %}">LOOK <i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
          <div class="card card-3">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h2 class="card__title">SPORTS</h2>
            <p class="card__apply">
              <a class="card__link" href="{% url 'core:sports' %}">LOOK<i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
          <div class="card card-4">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h2 class="card__title">Flights</h2>
            <p class="card__apply">
              <a class="card__link" href="#">Apply Now <i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
          <div class="card card-5">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h2 class="card__title">Hotels</h2>
            <p class="card__apply">
              <a class="card__link" href="#">Apply Now <i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
          <div class="card card-1">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h2 class="card__title">Weather</h2>
            <p class="card__apply">
              <a class="card__link" href="#">Apply Now <i class="fas fa-arrow-right"></i></a>
            </p>
          </div>
        </div>
      </div>
    {% endblock content %}

    {% else %}

    <h1>ERROR 404 not Found</h1>
    {% endif %}
           
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/messages.html
{% if messages %}
<div>
    {% for message in messages %}

    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
      </div>
    {% endfor %}
</div>
{% endif %}

core/templates/core/navbar.html
{% if user.is_authenticated %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
     
      <a class="navbar-brand" href="{% url 'core:home' %}">NEWSRADAR</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      </div>
      <div id="navbarNav">
        <ul class="navbar-nav mr-auto">
          
      
        </ul>
      </div>
      <div>
         <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 {{ user.username }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href= "{% url 'users:password-reset' %}">Reset Password</a>
                </li>
                <li>
                 <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                 </li>
          </ul>
        
            {% else %}
    
            {% endif %}
          </ul>
      </div>
    
  </nav>

core/templates/core/sports.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>
    <style>
  h1 {

margin: 0 auto;
text-align: center;
padding: 10px ;
}
    </style>
    <body>
        <div>
          
            <div>
                {% if user.is_authenticated %}
                {% block content %}
                
             <h1> SPORTS</h1>
             <rssapp-ticker id="tF50R6vajAA7qaj9"></rssapp-ticker><script src="https://widget.rss.app/v1/ticker.js" type="text/javascript" async></script>

             <rssapp-imageboard id="tF50R6vajAA7qaj9"></rssapp-imageboard><script src="https://widget.rss.app/v1/imageboard.js" type="text/javascript" async></script>
             {% endblock content %}
             {% else %}

            <h1>ERROR 404 not Found</h1>
            {% endif %}
            
        </div>
    </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
</body>
</html>

core/templates/core/stocks.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    </head>
    <style>
  h1 {

margin: 0 auto;
text-align: center;
padding: 10px ;
}
 </style>
<body>
<div>
{% if user.is_authenticated %}
{% include "core/navbar.html" %}  
{% include "core/messages.html" %} 
{% block content%}
<h1>Stocks</h1>
       <!-- TradingView Widget BEGIN -->
       <div class="tradingview-widget-container">
        <div class="tradingview-widget-container__widget"></div>
       <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/markets/" rel="noopener" target="_blank"><span class="blue-text"></span></a></div>
      <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>
    {
    "symbols": [
      {
        "description": "",
        "proName": "NASDAQ:AAPL"
      },
      {
        "description": "",
        "proName": "NASDAQ:TSLA"
      },
      {
        "description": "",
        "proName": "NASDAQ:AMZN"
      },
      {
        "description": "",
        "proName": "NASDAQ:NVDA"
      },
      {
        "description": "",
        "proName": "NYSE:AMC"
      },
      {
        "description": "",
        "proName": "NSE:RELIANCE"
      },
      {
        "description": "",
        "proName": "NASDAQ:META"
      },
      {
        "description": "",
        "proName": "NASDAQ:MSFT"
      },
      {
        "description": "",
        "proName": "NASDAQ:NFLX"
      },
      {
        "description": "",
        "proName": "NSE:TATAMOTORS"
      }
    ],
    "showSymbolLogo": true,
    "colorTheme": "light",
    "isTransparent": false,
    "displayMode": "adaptive",
    "locale": "en"
  }
    </script>
  </div>
  <!-- TradingView Widget END -->


  <!-- TradingView Widget BEGIN -->
   <div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/markets/" rel="noopener" target="_blank"><span class="blue-text"></span></a></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js" async>
    {
    "colorTheme": "light",
    "dateRange": "12M",
    "showChart": true,
    "locale": "en",
    "largeChartUrl": "",
    "isTransparent": false,
    "showSymbolLogo": true,
    "showFloatingTooltip": false,
    "width": "1300",
    "height": "1000",
    "plotLineColorGrowing": "rgba(41, 98, 255, 1)",
    "plotLineColorFalling": "rgba(41, 98, 255, 1)",
    "gridLineColor": "rgba(240, 243, 250, 0)",
    "scaleFontColor": "rgba(120, 123, 134, 1)",
    "belowLineFillColorGrowing": "rgba(41, 98, 255, 0.12)",
    "belowLineFillColorFalling": "rgba(41, 98, 255, 0.12)",
    "belowLineFillColorGrowingBottom": "rgba(41, 98, 255, 0)",
    "belowLineFillColorFallingBottom": "rgba(41, 98, 255, 0)",
    "symbolActiveColor": "rgba(41, 98, 255, 0.12)",
    "tabs": [
      {
        "title": "Indices",
        "symbols": [
          {
            "s": "NASDAQ:AAPL"
          },
          {
            "s": "AMEX:SPY"
          },
          {
            "s": "NASDAQ:TSLA"
          },
          {
            "s": "NASDAQ:AMZN"
          },
          {
            "s": "NASDAQ:AMD"
          },
          {
            "s": "NASDAQ:NVDA"
          },
          {
            "s": "NSE:RELIANCE"
          },
          {
            "s": "NASDAQ:META"
          },
          {
            "s": "NASDAQ:MSFT"
          },
          {
            "s": "NASDAQ:COIN"
          },
          {
            "s": "NSE:HDFCBANK"
          },
          {
            "s": "NSE:ICICIBANK"
          },
          {
            "s": "NASDAQ:NFLX"
          },
          {
            "s": "NSE:SBIN"
          },
          {
            "s": "NSE:TATAMOTORS"
          },
          {
            "s": "NYSE:BABA"
          },
          {
            "s": "NSE:AXISBANK"
          },
          {
            "s": "NASDAQ:GOOGL"
          },
          {
            "s": "NSE:WIPRO"
          }
        ],
        "originalTitle": "Indices"
      },
      {
        "title": "Futures",
        "symbols": [
          {
            "s": "CME_MINI:ES1!",
            "d": "S&P 500"
          },
          {
            "s": "CME:6E1!",
            "d": "Euro"
          },
          {
            "s": "COMEX:GC1!",
            "d": "Gold"
          },
          {
            "s": "NYMEX:CL1!",
            "d": "Crude Oil"
          },
          {
            "s": "NYMEX:NG1!",
            "d": "Natural Gas"
          },
          {
            "s": "CBOT:ZC1!",
            "d": "Corn"
          }
        ],
        "originalTitle": "Futures"
      },
      {
        "title": "Bonds",
        "symbols": [
          {
            "s": "CME:GE1!",
            "d": "Eurodollar"
          },
          {
            "s": "CBOT:ZB1!",
            "d": "T-Bond"
          },
          {
            "s": "CBOT:UB1!",
            "d": "Ultra T-Bond"
          },
          {
            "s": "EUREX:FGBL1!",
            "d": "Euro Bund"
          },
          {
            "s": "EUREX:FBTP1!",
            "d": "Euro BTP"
          },
          {
            "s": "EUREX:FGBM1!",
            "d": "Euro BOBL"
          }
        ],
        "originalTitle": "Bonds"
      },
      {
        "title": "Forex",
        "symbols": [
          {
            "s": "FX:EURUSD",
            "d": "EUR/USD"
          },
          {
            "s": "FX:GBPUSD",
            "d": "GBP/USD"
          },
          {
            "s": "FX:USDJPY",
            "d": "USD/JPY"
          },
          {
            "s": "FX:USDCHF",
            "d": "USD/CHF"
          },
          {
            "s": "FX:AUDUSD",
            "d": "AUD/USD"
          },
          {
            "s": "FX:USDCAD",
            "d": "USD/CAD"
          }
        ],
        "originalTitle": "Forex"
      }
    ]
  }
    </script>
  </div>
  <!-- TradingView Widget END -->   
       
{% endblock content %}
{% else %}

<h1>ERROR 404 not Found</h1>

{% endif %}
</div>
 
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    
</body>
</html>